# 生产环境配置
spring:
  profiles:
    active: prod

  # 数据库配置
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/trip_dog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123123}
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 连接池配置
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 30000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

  # Session配置
  session:
    timeout: 30m       # Session超时时间

  # 邮件配置（生产环境请使用环境变量）
  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# 服务器配置
server:
  port: ${SERVER_PORT:7979}
  servlet:
    context-path: /
    session:
      timeout: 30m

  # 生产环境推荐启用压缩
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.tripdog.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

# 日志配置
logging:
  level:
    root: INFO
    com.tripdog: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/tripdog-backend.log
    max-size: 100MB
    max-history: 30

# Actuator配置（用于健康检查和监控）
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
  health:
    db:
      enabled: true

# 应用信息
info:
  app:
    name: TripDog Backend
    version: 1.0.0
    description: TripDog旅行伴侣后端服务
