spring:
  application:
    name: tripdog-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:ai}
  session:
    timeout: 30m
  # Web配置
  web:
    resources:
      add-mappings: true

  datasource:
    url: jdbc:mysql://localhost:3306/trip_dog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  # 邮件配置
  mail:
    host: ${MAIL_HOST:smtp.qq.com}
    port: ${MAIL_PORT:465}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true  # 启用SSL
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

server:
  port: ${SERVER_PORT:7979}
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 支持跨域的其他配置
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.tripdog: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.tripdog.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# minio
minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_AK}
  secret-key: ${MINIO_SK}
  bucket-name: trip-doge

# CORS 跨域配置
cors:
  # 允许的源域名，多个用逗号分隔
  # 开发环境常用端口 + 生产环境域名
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080,http://localhost:5173,http://localhost:4200,http://127.0.0.1:3000,http://127.0.0.1:8080,http://127.0.0.1:5173,http://127.0.0.1:4200,https://trip-doge-frontend.zeabur.app}
  # 是否允许携带凭证
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

